version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./etc:/app/etc
    environment:
      - GIN_MODE=release
