-- 校区和地点初始化数据
DELETE FROM locations;
DELETE FROM campuses;

-- 自动生成ID
DELETE FROM sqlite_sequence WHERE name IN ('campuses', 'locations');

-- 插入校区数据
INSERT INTO campuses (name, is_active, sort_order, created_at, updated_at) VALUES
('普陀校区', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('闵行校区', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('滴水湖校区', 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 插入地点数据
-- 普陀校区地点（华东师范大学普陀校区，中山北路校区）
-- 中心坐标约: 31.2304, 121.4245
INSERT INTO locations (campus_id, name, category, latitude, longitude, is_active, sort_order, memory_count, created_at, updated_at) VALUES
(1, '图书馆', 'academic', 31.2304, 121.4245, 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '三馆', 'academic', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '博学楼', 'academic', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '干训楼', 'academic', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '化学馆', 'academic', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '俊秀楼', 'academic', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '科教楼（脑所）', 'academic', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '数学馆', 'academic', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '体育楼', 'academic', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '微波所', 'academic', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '文附楼', 'academic', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '文史楼（群贤堂）', 'academic', 1, 12, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '物理楼', 'academic', 1, 13, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '小教楼', 'academic', 1, 14, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '专家楼', 'academic', 1, 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '电镜中心', 'academic', 1, 16, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '计算机楼', 'academic', 1, 17, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '理科大楼', 'academic', 1, 18, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '时尚中心', 'academic', 1, 19, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '文科大楼', 'academic', 1, 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '新四教室', 'academic', 1, 21, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '国际教育楼', 'academic', 1, 22, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '对外汉语学院', 'academic', 1, 23, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '公共管理学院', 'academic', 1, 24, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '开放教育学院', 'academic', 1, 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '对外汉语教学楼', 'academic', 1, 26, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '田家炳教育书院', 'academic', 1, 27, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '办公楼', 'activity', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '博群堂', 'activity', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '出版社', 'activity', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '档案馆', 'activity', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '孟刘馆', 'activity', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '思群堂', 'activity', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '校史馆', 'activity', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '游泳池', 'activity', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '老图书馆', 'activity', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '老干部活动室', 'activity', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '大学生活动中心', 'activity', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '河西食堂', 'dining', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '河东食堂', 'dining', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '丽娃食堂', 'dining', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '第三宿舍', 'dormitory', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第五宿舍', 'dormitory', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第七宿舍', 'dormitory', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第八宿舍', 'dormitory', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十宿舍', 'dormitory', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十一宿舍', 'dormitory', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十二宿舍', 'dormitory', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十五宿舍', 'dormitory', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十六宿舍', 'dormitory', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十七宿舍', 'dormitory', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十八宿舍', 'dormitory', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '第十二宿舍', 'dormitory', 1, 12, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '留学生公寓', 'dormitory', 1, 13, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '大草坪', 'outdoor', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '爱之坪', 'outdoor', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '校医院', 'service', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '大师屋', 'service', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '牛奶棚', 'service', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '校工会', 'service', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '信息办', 'service', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '丽娃浴室', 'service', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '全能数码', 'service', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '后勤保障部', 'service', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '全家便利店', 'service', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '慈善爱心屋', 'service', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '丽娃综合商场', 'service', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, '体育馆', 'sports', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '共青场', 'sports', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '丽娃操场', 'sports', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '篮球场', 'sports', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '共青运动区', 'sports', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


-- 闵行校区地点
(2, '图书馆（桶楼）', 'academic', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '图书馆（裙楼）', 'academic', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '办公楼', 'academic', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '第一教学楼', 'academic', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '第二教学楼', 'academic', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '第三教学楼', 'academic', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '第四教学楼', 'academic', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '物理楼', 'academic', 1, 3, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '信息技术楼', 'academic', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '数学楼', 'academic', 1,10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '法商楼', 'academic', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '外语学院', 'academic', 1, 12, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '历史学系', 'academic', 1, 13, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '中文系', 'academic', 1, 14, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '化学与分子工程学院', 'academic', 1, 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '生命科学学院', 'academic', 1, 16, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '资环楼', 'academic', 1, 17, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '美术系', 'academic', 1, 18, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '实验A楼', 'academic', 1, 19, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '实验B楼', 'academic', 1, 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '法学院', 'academic', 1, 21, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '体育与健康学院', 'academic', 1, 22, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '河口海岸大楼', 'academic', 1, 23, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, '学生之家', 'activity', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '孟宪承书院', 'activity', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


(2, '游泳馆', 'sports', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '体育馆', 'sports', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '排球场', 'sports', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '田径馆', 'sports', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '羽毛球馆', 'sports', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '河东篮球场', 'sports', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '河西篮球场', 'sports', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '河东足球场', 'sports', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '河西足球场', 'sports', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '西运动场', 'sports', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '东运动场', 'sports', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


(2, '保卫处', 'service', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '校医院', 'service', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '联华超市', 'service', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '学生共享空间', 'service', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, '剑川路学生公寓', 'dormitory', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第1宿舍', 'dormitory', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第2宿舍', 'dormitory', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第3宿舍', 'dormitory', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第4宿舍', 'dormitory', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第5宿舍', 'dormitory', 1, 6, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第6宿舍', 'dormitory', 1, 7, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第7宿舍', 'dormitory', 1, 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第8宿舍', 'dormitory', 1, 9, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第9宿舍', 'dormitory', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第10宿舍', 'dormitory', 1, 11, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第11宿舍', 'dormitory', 1, 12, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第12宿舍', 'dormitory', 1, 13, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第13宿舍', 'dormitory', 1, 14, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第14宿舍', 'dormitory', 1, 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第15宿舍', 'dormitory', 1, 16, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第16宿舍', 'dormitory', 1, 17, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第17宿舍', 'dormitory', 1, 18, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第18宿舍', 'dormitory', 1, 19, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第19宿舍', 'dormitory', 1, 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第20宿舍', 'dormitory', 1, 21, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第21宿舍', 'dormitory', 1, 22, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '本科生第22宿舍', 'dormitory', 1, 23, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第1宿舍', 'dormitory', 1, 24, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第2宿舍', 'dormitory', 1, 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第3宿舍', 'dormitory', 1, 26, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第4宿舍', 'dormitory', 1, 27, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第5宿舍', 'dormitory', 1, 28, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第6宿舍', 'dormitory', 1, 29, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第7宿舍', 'dormitory', 1, 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第8宿舍', 'dormitory', 1, 31, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第9宿舍', 'dormitory', 1, 32, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第10宿舍', 'dormitory', 1, 33, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第11宿舍', 'dormitory', 1, 34, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第12宿舍', 'dormitory', 1, 35, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第13宿舍', 'dormitory', 1, 36, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第14宿舍', 'dormitory', 1, 37, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第15宿舍', 'dormitory', 1, 38, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第16宿舍', 'dormitory', 1, 39, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '研究生第17宿舍', 'dormitory', 1, 40, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, '冬月厅', 'dining', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '秋实阁', 'dining', 1, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '秋林阁', 'dining', 1, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '夏雨厅', 'dining', 1, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '冬日餐厅', 'dining', 1, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 临港校区地点

SELECT '初始化完成: ' || COUNT(*) || '个校区, ' ||
       (SELECT COUNT(*) FROM locations) || '个地点'
FROM campuses;